<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bttn_control_bar_product</name>
   <tag></tag>
   <elementGuidId>b408e782-67a8-4954-b704-988d4f3af63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hd-control-bar']/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hd-drawer-container > #hd-drawer > #hd-control-bar > #hd-close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>438c6b53-187f-4643-b479-32f066fd44a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hd-close-button</value>
      <webElementGuid>708a3ce6-6cbb-40c7-bb44-87ef33cedd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drawer-close-button</value>
      <webElementGuid>33fd6c41-84f7-476e-813a-15ebcb6b0fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>a3f7c80b-4191-49d3-8b2e-50296a51a6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;hd-drawer-container&quot;]/div[@id=&quot;hd-drawer&quot;]/div[@id=&quot;hd-control-bar&quot;]/button[@id=&quot;hd-close-button&quot;]</value>
      <webElementGuid>4fc9d450-7e02-484a-b1ba-35aa53bc8e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4279ef4-4254-466e-a0e0-810933c27b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hd-control-bar']/button[2]</value>
      <webElementGuid>81edbb21-1229-4dd6-a0f0-0f8354ba3777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>c3eb8678-ec13-4eff-a99a-3965969c78d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'hd-close-button']</value>
      <webElementGuid>6e2d00aa-7ba0-4169-b892-69211dafdb12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
