<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_added_basket</name>
   <tag></tag>
   <elementGuidId>e6d8ae79-1d64-4da3-9bb4-ed3673e09569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;View Basket 3 × “Android Quick Start Guide” have been added to your basket.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaf9735c-518b-4feb-a424-1ac89875e26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-message</value>
      <webElementGuid>2ecc75e9-5c51-40c4-844e-d9698ff615ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Basket 3 × “Android Quick Start Guide” have been added to your basket.</value>
      <webElementGuid>0bdb7acd-4ccc-4fca-b72c-dc8f110132c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;woocommerce-message&quot;]</value>
      <webElementGuid>b4318a97-ad1b-4fc0-ad02-777ba93e7da0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div</value>
      <webElementGuid>39007326-2894-4e8b-a970-125909e628ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[1]/following::div[1]</value>
      <webElementGuid>29542a9f-dfdf-4749-aa54-1e798b2ead84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[1]</value>
      <webElementGuid>68b464bd-8678-48b2-940f-178ca80fa029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[1]/preceding::div[1]</value>
      <webElementGuid>15aa9b99-9c14-4ce5-af1a-8dd2ea9277bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3 × “Android Quick Start Guide” have been added to your basket.']/parent::*</value>
      <webElementGuid>ee592fa0-c466-4a62-87b8-0f542ab23955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>96bd54d4-1bb7-4702-9bab-e0f7adb3bcc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'View Basket 3 × “Android Quick Start Guide” have been added to your basket.' or . = 'View Basket 3 × “Android Quick Start Guide” have been added to your basket.')]</value>
      <webElementGuid>6a2ebc31-4a98-4e4e-9346-9091bf4915ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
