<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_item_basket_and_price</name>
   <tag></tag>
   <elementGuidId>ee450155-6416-4377-85a3-f5a940bf883f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wpmenucartli']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wpmenucart-contents.empty-wpmenucart-visible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; 0 items -₹0.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f30b35c-4fdf-4a84-befe-e863b52b425a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpmenucart-contents empty-wpmenucart-visible</value>
      <webElementGuid>83cf2b25-a358-4223-97a8-b84a5f401b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/shop/</value>
      <webElementGuid>fdcb6e77-7b3c-41d6-bdac-4dc6d54f3694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Start shopping</value>
      <webElementGuid>1c90c7e9-f3cf-418b-ad8f-776418cbab1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0 items₹0.00</value>
      <webElementGuid>4ef09037-0deb-4a2e-83b8-fe1fe2b39930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpmenucartli&quot;)/a[@class=&quot;wpmenucart-contents empty-wpmenucart-visible&quot;]</value>
      <webElementGuid>8228cae6-6479-4169-b162-78f7290a0bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wpmenucartli']/a</value>
      <webElementGuid>6ecfda29-c12b-444e-be55-76d5050da2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site'])[1]/following::a[1]</value>
      <webElementGuid>e4b43d67-1340-4e26-8d52-c66f2184d063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AT Site'])[1]/following::a[2]</value>
      <webElementGuid>b6a01304-ec49-467b-b5fb-9bce61e187b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[3]</value>
      <webElementGuid>c0857a2e-b823-4ce7-a1fc-f1ae8f4b9af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://practice.automationtesting.in/shop/')])[2]</value>
      <webElementGuid>2fa54a45-b6d4-46ae-950e-9c1bce73b2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>c1a254e6-26d9-4e2f-8e51-9e1796623b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/shop/' and @title = 'Start shopping' and (text() = '0 items₹0.00' or . = '0 items₹0.00')]</value>
      <webElementGuid>4fdfa849-5148-44cc-a576-89f18d721d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
