<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_province</name>
   <tag></tag>
   <elementGuidId>fe8ca749-6eff-4036-8c3f-fc701ff04307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-result-label-41</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-results-2']/li/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;DKI Jakarta&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b08bd6a9-56af-455c-9c4f-847896901458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-result-label</value>
      <webElementGuid>04c2a6a7-213b-4c21-a7c2-a086e94c40d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-result-label-41</value>
      <webElementGuid>3d03eae5-2420-4a40-8dd2-b4e28a207ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3f0934e0-40f8-4a5c-8199-77d8e7264b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DKI Jakarta</value>
      <webElementGuid>2df849f1-d872-4bf5-92a5-fffb65f0b24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-result-label-41&quot;)</value>
      <webElementGuid>49c9f6ec-07ee-48b9-9e13-cde9ce02ee13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='select2-result-label-41']</value>
      <webElementGuid>ed88edb3-5a2e-479e-8c48-9f53aad693ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-results-2']/li/div</value>
      <webElementGuid>728e1979-3813-4415-a240-40063a573cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::div[1]</value>
      <webElementGuid>50dd0619-8ec8-4217-a625-0a4e2493e71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jakarta']/parent::*</value>
      <webElementGuid>842f228c-72ff-4a1a-9373-4f8090ba7289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li/div</value>
      <webElementGuid>70639758-125c-4c43-9cdb-f57a0bc54fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'select2-result-label-41' and (text() = 'DKI Jakarta' or . = 'DKI Jakarta')]</value>
      <webElementGuid>f487f8a5-4201-4e53-8754-80e8fb4f1e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
