<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_coupon_code</name>
   <tag></tag>
   <elementGuidId>e1890c5b-e23e-43be-bce9-6df0b979db18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Coupon code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fcdedd0-4f81-4f98-973a-970ad555150b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c3a7758-89e1-4bee-8215-4e29498644d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>8adb68b6-0ce2-4dc1-9ed9-849820492718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>e84881c8-b8f8-4fc9-82c5-08a6220bbfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>8fe6a93c-9ddd-45fe-be38-fd12fd8c2af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Coupon code</value>
      <webElementGuid>a3c50876-8960-42ee-833b-0dfd91c5b9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon_code&quot;)</value>
      <webElementGuid>316c558d-b218-475e-9139-6cc188782a87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon_code']</value>
      <webElementGuid>cab0f06e-bda4-4882-9cb0-c9c2860f55fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-34']/div/div/form/table/tbody/tr[2]/td/div/input</value>
      <webElementGuid>eadf4dd7-2bb2-4d9a-a73f-07454b5b5570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/input</value>
      <webElementGuid>19ed1327-9730-40dc-8958-9bd43d6cceca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'coupon_code' and @id = 'coupon_code' and @placeholder = 'Coupon code']</value>
      <webElementGuid>d4dd747d-87b3-454a-8f42-a898cbef6e6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
